### ISSUE TITLE
Create API tokens

### ISSUE THREAD

**Issue by mimurawil** [thisdot/movies-api#1]
Contenful tokens. Do we need other tokens?

**Comment by jesus4497** [comment]
So far, I created the following tokens on Contentful, I don't think we need anything else:

CONTENTFUL_SPACE_ID
CONTENTFUL_CONTENT_DELIVERY_API_TOKEN
CONTENTFUL_CONTENT_MANAGEMENT_API_TOKEN

AWS tokens will be handled later in the development
